Box/urls.py
from django.contrib import admin
from django.urls import path
from box_app.views import (UserCreateView, MainView, LoginView, UserLogoutView, BaseView, BoxingClassDetailView,
                           TrainerView, StudentView, SearchView, AddStudentView, AddTrainerView, AddStudentSuccessView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('add_user/', UserCreateView.as_view(), name='add_user'),
    path('', MainView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('base/', BaseView.as_view(), name='baza'),
    path('boxing_class/<int:pk>/', BoxingClassDetailView.as_view(), name='boxing_class_detail'),
    path('trainer_detail/<int:trainer_id>/', TrainerView.as_view(), name='trainer_detail'),
    path('student_detail/<int:student_id>/', StudentView.as_view(), name='student_detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('add_student/', AddStudentView.as_view(), name="add_student"),
    path('add_trainer/', AddTrainerView.as_view(), name="add_trainer"),
    path('add_student_success/', AddStudentSuccessView.as_view(), name="add_student_success")



]

box_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


class BoxingClass(models.Model):
    class_name = models.CharField(max_length=20)
    level_choices = [
        ('1', 'Podstawowy'),
        ('2', 'Średnio-zaawansowany'),
        ('3', 'Zaawansowany'),
    ]
    level = models.CharField(max_length=1, choices=level_choices)
    teacher = models.ForeignKey('User', on_delete=models.CASCADE, null=True, blank=True,
                                limit_choices_to={'is_teacher': True}, related_name='classes_as_teacher')
    students = models.ManyToManyField('User', through='BoxingClassMembership', limit_choices_to={'is_student': True}, related_name='classes_as_student')

    def __str__(self):
        return f'{self.class_name}'


class BoxingClassMembership(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='class_memberships',
                                limit_choices_to={'is_student': True})
    boxing_class = models.ForeignKey(BoxingClass, on_delete=models.CASCADE, related_name='class_memberships')


class Profile(models.Model):
    age = models.PositiveIntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    teachers = models.ManyToManyField(User, related_name='students')
    students = models.ManyToManyField(User, related_name='teachers')
    #type = models.ForeignKey(User, on_delete=models.CASCADE, primary_key=True)



CHOICES = (
    (1, "Student"),
    (2, "Trainer"),
)

templates/Trainer.html
{% extends "base.html" %}

{% block title %}
    Detale Trenera
{%  endblock %}

{% block content %}
    
    <p>imie: {{ trainer.name }}</p>
    <p>nazwisko: {{ trainer.surname }}</p>
    <p>wiek: {{ trainer.age }}</p>
    <p>mail:{{ trainer.email }}</p>

{% if student %}
        <h2>Przypisany Student:</h2>
        <p>
        <a href="{% url 'student_detail' student.id %}">{{ student.name }} {{ student.surname }}</a>
    </p>
    {% else %}
        <p>Brak przypisanego studenta.</p>
    {% endif %}

    <h3>klasy w ktorych uczy </h3>
    <ul>
    {% for ta in taught %}
        <li>{{ ta.class_name}}</li>
    {% endfor %}
    </ul>
{% endblock %}

templates/add_student.html
{% extends "base.html" %}

{% block title %}
Zapis nowego ucznia
{% endblock %}

{% block content %}
<h2>Przyjęcie nowego ucznia</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Dodaj ucznia</button>
    </form>
{% endblock %}

templates/add_student_success.html
{% extends "base.html" %}

{% block title %}
Zgłoszenie nowego ucznia
{% endblock %}

{% block content %}
<h3>Twoje przyjęcie zostało zgłoszone, możesz wrócić do <a href="{% url 'index' %}">strony głównej</a>.</h3>
    
     <p>imie: {{ student.name }}</p>
    <p>nazwisko: {{ student.surname }}</p>
    <p>wiek: {{ student.age }}</p>
    <p>mail:{{ student.email }}</p>

    {% if student.teachers.all %}
        <h2>Zajęcia indywidualne u :</h2>
        {% for trainer in student.teachers.all %}
            <p>{{ trainer.name }} {{ trainer.surname }}</p>
        {% endfor %}
    {% else %}
        <p>Brak przypisanego trenera.</p>
    {% endif %}
{% endblock %}

templates/add_student_success2.html
{% extends "base.html" %}

{% block title %}
Zgłoszenie nowego ucznia
{% endblock %}

{% block content %}
<h3>Twoje przyjęcie zostało zgłoszone, możesz wrócić do <a href="{% url 'index' %}">strony głównej</a>.</h3>
    

{% endblock %}

templates/add_trainer.html
<

{% extends 'base.html' %} 

{% block content %}
  <h2>Add a new trainer</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Main Page{% endblock %}</title>

    <style>
        body {
            margin: 0;
            padding: 0;
        }

        .header {
            background-color: #f2f2f2;
            padding: 10px;
            text-align: right;
        }

        .logout-link {
            margin-right: 10px;
        }
    </style>
</head>
<body>

<div class="header">
    {% if user.is_authenticated %}
        <a class="logout-link" href="{% url 'logout' %}?next={% url 'baza' %}">Wyloguj się</a>
    {% endif %}
</div>

<h1>Szkoła bokserska.</h1>

{% for boxing_class in boxingclassess %}
    <h2>{{ boxing_class.name }}</h2>
    <p>{{ boxing_class.description }}</p>
    <a href="{% url 'boxing_class_detail' pk=boxing_class.pk %}">{{ boxing_class.class_name }} </a><br>
{% endfor %}

{% block content %}
    <p>
        <a href="{% url 'add_student' %}"><b>Zapisz się do klasy bokserskiej</b></a>
    </p>
    
    <p>
        <a href="{% url 'search' %}"><b>Wyszukaj trenera</b></a>
    </p>
{% endblock %}


{% block footer %}
<hr>
&copy; 2023 ONL_PYT_W_29
{% endblock %}

</body>
</html>

templates/baza.html
<footer>
    {% if user.is_authenticated %}
        <p>Aktualnie zalogowany użytkownik: {{ user.username }}</p>
        <a href="{% url 'logout' %}?next={% url 'index' %}">Wyloguj</a>
    {% else %}
        <p><a href="/login">Zaloguj się</a></p>
        <p><a href="{% url 'add_user' %}">Zarejestruj się</a></p>
    {% endif %}
</footer>

templates/boxing_class_detail.html
{% extends "base.html" %}

{% block title %}
    Detale Klasy Bokserskiej
{%  endblock %}

{% block content %}
    <h1>{{ boxing_class.class_name }}</h1>
    <p>Poziom: {{ boxing_class.get_level_display }}</p>
      <p>Nauczyciel:
        <a href="{% url 'trainer_detail' trainer_id=boxing_class.teacher.id %}">
            {{ boxing_class.teacher.name }} {{ boxing_class.teacher.surname }}
        </a>
    </p>
    <p>Studenci:</p>
    <ul>
        {% for student in boxing_class.students.all %}
            <li>{{ student.name }} {{ student.surname }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</body>
</html>

templates/search.html
{% extends "base.html" %}

{% block title %}
    Wyszukiwanie trenera
{% endblock %}

{% block content %}
<h2>Wyszukiwanie trenera</h2>
    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Szukaj</button>
    </form>

{% if trainer%}
        <h2>Wynik wyszukiwania:</h2>
        <ul>
        {% for tr in trainer%}
            <li><a href="{% url "trainer_detail" tr.pk %}">{{ tr }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/student.html
{% extends "base.html" %}

{% block title %}
    Detale Ucznia
{%  endblock %}

{% block content %}
    <h1>{{ student.id }}</h1>
    <p>imie: {{ student.name }}</p>
    <p>nazwisko: {{ student.surname }}</p>
    <p>wiek: {{ student.age }}</p>
    <p>mail:{{ student.email }}</p>

    {% if student.teachers.all %}
        <h2>Zajęcia indywidualne u :</h2>
        {% for trainer in student.teachers.all %}
            <p>{{ trainer.name }} {{ trainer.surname }}</p>
        {% endfor %}
    {% else %}
        <p>Brak przypisanego trenera.</p>
    {% endif %}

{% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>

</body>
</html>